# Generated by Django 5.1.5 on 2025-01-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vote_unique_together'),
    ]

    operations = [
    ]
# polls/migrations/0003_remove_duplicate_votes.py
from django.db import migrations
from django.db.models import Count

def remove_duplicate_votes(apps, schema_editor):
    Vote = apps.get_model("polls", "Vote")
    # Find all duplicates: group by poll and voter, and count votes
    duplicates = (
        Vote.objects
        .values('poll_id', 'voter_id')
        .annotate(vote_count=Count('id'))
        .filter(vote_count__gt=1)
    )
    for duplicate in duplicates:
        poll_id = duplicate['poll_id']
        voter_id = duplicate['voter_id']
        # Get all votes for that poll and voter
        votes = list(Vote.objects.filter(poll_id=poll_id, voter_id=voter_id).order_by('id'))
        # Keep the first vote and delete the rest
        for vote in votes[1:]:
            vote.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_votes),
    ]
