# Generated by Django 5.1.5 on 2025-01-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20250201_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: set an expiration date for the poll', null=True),
        ),
    ]
