# Generated by Django 5.1.5 on 2025-01-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes (e.g., 120 for 2 hours)'),
        ),
    ]
